# Generated by Django 6.0 on 2025-12-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_child_enfant_histoire_delete_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField()),
                ('histoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.histoire')),
            ],
        ),
    ]
