# Generated by Django 6.0 on 2025-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_chapitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='histoire',
            name='morale',
            field=models.TextField(blank=True),
        ),
    ]
