# Generated by Django 6.0 on 2025-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_histoire_morale'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
