# Generated by Django 6.0 on 2025-12-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_chapitre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapitres/'),
        ),
    ]
