# Generated by Django 6.0 on 2025-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_chapitre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
