# Generated by Django 6.0 on 2025-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_chapitre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='image',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='prompt_image',
            field=models.TextField(blank=True),
        ),
    ]
