# Generated by Django 6.0 on 2025-12-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_chapitre_image_chapitre_prompt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='prompt_image',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
