# Generated by Django 6.0 on 2025-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_remove_chapitre_prompt_image_chapitre_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='image',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image_base64',
            field=models.TextField(blank=True),
        ),
    ]
