# Generated by Django 6.0 on 2025-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_remove_chapitre_image_chapitre_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='prompt_image',
            field=models.TextField(blank=True),
        ),
    ]
