# Generated by Django 6.0 on 2025-12-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_chapitre_prompt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='prompt_image',
        ),
    ]
