# Generated by Django 6.0 on 2026-01-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_remove_chapitre_prompt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='image_derniere_erreur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image_statut',
            field=models.CharField(choices=[('pas_commence', 'Pas commencé'), ('en_cours', 'En cours'), ('ok', 'OK'), ('erreur', 'Erreur')], default='pas_commence', max_length=20),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image_tentatives',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
